app:
  client:
    host: ${CLIENT_HOST}
  oauth2:
    provider:
      google:
        id: google
        secret: google
spring:
  profiles:
    active: ${ENVIRONMENT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
